### ISSUE TITLE
Microsoft.Bot.Builder.Solutions Points to this Repo as its Source Repository

### ISSUE THREAD

**Issue by DavidStrickland0** [microsoft/AI#15]
The Microsoft.Bot.Builder.Solutions Nuget Package points as this Repo as the Project Url
On Nuget this Project is also listed as the Source Repository

However neither is accurate Likely not an issue with this project as much as with the project that has this project listed but given I cant find that repository to log the issue.

Any guesses who or where Microsoft.Bot.Builder.Solutions actually is?

**Comment by dciborow** [comment]
I am looking into this....

**Comment by DavidStrickland0** [comment]
For what it's worth the bug that sent me on this quest was in part that Microsoft.Bot.Builder.Solutions has recently deprecated a huge chunk of code in favour of the code in  Microsoft.Bot.Solutions which I think is the code at https://github.com/microsoft/botframework-solutions. However Microsoft.Bot.Solutions also seems to claim this site as its Project url and source repository.
