### ISSUE TITLE
Error in Creating new Project under VS 2019 Using the Virtual Assistant Template

### ISSUE THREAD

**Issue by MersGitHub** [microsoft/AI#6]
After installing all prerequisites for the Azure Bot Virtual Assistant on my laptop, I have selected on Virtual Studio 2019 new project. On the windows that new project select opened, I have selected the Virtual Assistant Template which guide with another windows the configuration of the new project with the Virtual Assistant template. Using the default configuration provided, I selected the Create action (versus go back). 

I then encounter the following error - Refer here to attached Word document that has the errors windows that are occurring for this issue,

[Issue when attempting to create new project with Virtual Assistant Template using Virtual Studio 2019.docx](https://github.com/microsoft/AI/files/3790920/Issue.when.attempting.to.create.new.project.with.Virtual.Assistant.Template.using.Virtual.Studio.2019.docx)

**Comment by dciborow** [comment]
I'm sorry but the Azure Bot Virtual Assistant is not covered in this repo.

**Comment by MersGitHub** [comment]
Thank you Daniel for your feedback

I have ended on the issue site from the Bot Framework Solutions URL -
https://github.com/microsoft/botframework-solutions/.

And this issue is associated with that Azure Bot Services.

Where can I report my issue, then, associated with the virtual assistant of
that Microsoft Azure Bot Services?

Thank you for your assistance and cooperation.

Sylvain
438-406-1854
